AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: notify rain
Resources:
  LineBotNotifyRainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./
      Events:
        MyLineBotNotifyRainApi:
          Type: Api
          Properties:
            Path: /LineBotNotifyRainResource
            Method: POST